theme: jekyll-theme-minimal
title: Aakash Mishra
description: Hi! My name is Aakash and I’m pursuing a Master’s in Computer Science and Engineering from University of California, Santa Cruz. This is my personal website outlining my skills, background, work experience and interests.
